<?php
/**
 * Created by IntelliJ IDEA.
 * User: yuanguohong
 * Date: 2019/4/19
 * Time: 10:14
 * 测试中心管理后台访问控制
 */

namespace app\common\controller;

use think\App;
use think\Controller;
use app\common\model\Admin;

class AdminBase extends Controller
{

    public $admin_id = null;
    protected $token = null;
    public $user = null;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        // 获取用户登录信息
        // $id 用户的唯一标识
        // $token 用户登录的唯一标识
        $userInfo = session('userInfo');
        if(isset($userInfo['id']) && isset($userInfo['token'])){
            $this->admin_id = $userInfo['id'];
            $this->token = $userInfo['token'];

            // 验证用户是否存在
            $user = Admin::checkAdminIsNormal($this->admin_id);
            if($user) {
                $this->user = $user;
                return true;
            }

            throwError(401 , "用户不存在" , 401);
        }

        throwError(401 , "用户不存在" , 401);
    }
}