<?php
/**
 * Created by IntelliJ IDEA.
 * User: yuanguohong
 * Date: 2019/5/23
 * Time: 16:59
 */

namespace app\common\controller;


use app\common\model\Admin;
use think\Controller;
use Encode;
use think\facade\Request;

class PersonnelBase extends Controller
{
    public $id=null;
    public $personnel=null;
    protected $token=null;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        // 获取用户登录信息
        $token = cookie('personnel_token');
        $token = Request::header('personnel_token');

        $this->token = $token;
        $array = json_decode(Encode::decrypt($token) , true);
        $personnelId = isset($array['id']) ? $array['id'] : 0;
        if(!empty($personnelId)){
            $personnel = Admin::checkWorkIsNormal($personnelId);
            if($personnel){
                $this->id = $personnelId;
                $this->personnel = $personnel;
                return true;
            }
        }
        $cookie = json_encode($_COOKIE);
//        cookie('personnel_token' , '');
        throwError(401 , "用户未登录-{$cookie}-$token" , 401);
    }


}