<?php
/**
 * Created by IntelliJ IDEA.
 * User: yuanguohong
 * Date: 2019/5/23
 * Time: 16:59
 */

namespace app\common\controller;


use app\common\model\User;
use think\Controller;
use Encode;
use think\facade\Request;

class UserBase extends Controller
{
    public $id=null;
    public $user=null;
    protected $token=null;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        // 获取用户登录信息
//        $token = cookie('user_token');
        $token = Request::header('user_token');
        $header = Request::header();
        $headerA = $_SERVER;

        $this->token = $token;
        $array = json_decode(Encode::decrypt($token) , true);
        $userId = isset($array['id']) ? $array['id'] : 0;
        if(!empty($userId)){
            $user = User::checkUser($userId);
            if($user){
                $this->id = $userId;
                $this->user = $user;
                return true;
            }
        }
        $cookie = json_encode($_COOKIE);
        $header = json_encode($header);
        $headerA = json_encode($headerA);

        throwError(401 , "用户未登录-{$cookie}-$token-$header-$headerA" , 401);
    }


}